export const ArtPageItem = [
    {
        key: 0,
        photoID: '12NoWGuc1_9Crp3wph4CeI6H3ae7DOs1X',
        artist: 'X | Twitter @NiixARTs',
        link: 'https://x.com/NiixARTs',
    },
    {
        key: 1,
        photoID: '13jmyyJadqU5DNIN_EANOB7nSJtw0hdF_',
        artist: 'X | Twitter @HirscheSly',
        link: 'https://x.com/HirscheSly',
    },
    {
        key: 2,
        photoID: '14_I2bj_uCGpDsnwqsUM8RJuNXQY4DYYl',
        artist: 'X | Twitter @Pentaagonkaa',
        link: 'https://x.com/Pentaagonkaa',
    },
    {
        key: 3,
        photoID: '1B7vJ2o_GpIT0kcqYEyPgbLi728-3pA_2',
        artist: 'X | Twitter @LoveIock_',
        link: 'https://x.com/LoveIock_',
    },
    {
        key: 4,
        photoID: '1QeQWTTj2GM6G7bsCG-H-KpKnU-RFXNhI',
        artist: 'X | Twitter @Beelzeryon',
        link: 'https://x.com/Beelzeryon',
    },
    {
        key: 5,
        photoID: '1UrAufq6bNPLSEQ6GTo1bLXKA3KOC00Qr',
        artist: 'X | Twitter @NiixARTs',
        link: 'https://x.com/NiixARTs',
    },
    {
        key: 6,
        photoID: '1EvL7mUMtT07RCe9hv9_MaHseNW9Hcuat',
        artist: 'X | Twitter @foxynalie',
        link: 'https://x.com/foxynalie',
    },
    {
        key: 7,
        photoID: '1GqBbR0lr79sT0eJICiZCmjKAHwkfqw_g',
        artist: 'X | Twitter @LoveIock_',
        link: 'https://x.com/LoveIock_',
    },
    {
        key: 8,
        photoID: '1Ipi_fjyaX2ma827XKpwCGWUga3_jz2l9',
        artist: 'X | Twitter @LoveIock_',
        link: 'https://x.com/LoveIock_',
    },
    {
        key: 9,
        photoID: '1JIGxYjARSef5Mor86WCjuM3XGthI2ngi',
        artist: 'X | Twitter @LoveIock_',
        link: 'https://x.com/LoveIock_',
    },
    {
        key: 10,
        photoID: '1Pk8jWzMrqCGNdUA3Bo7onXUE_lIHXNCX',
        artist: 'X | Twitter @LoveIock_',
        link: 'https://x.com/LoveIock_',
    },
    {
        key: 11,
        photoID: '1M42J2sPGUMLbX1OST5Q62VmMd3z5pKbN',
        artist: 'X | Twitter @CrowParadeArt',
        link: 'https://x.com/CrowParadeArt',
    },
    {
        key: 12,
        photoID: '1_yHyU7WNKH2KD36yOi0JbLVRkrv9mv4t',
        artist: 'X | Twitter @LoveIock_',
        link: 'https://x.com/LoveIock_',
    },
];
